### ISSUE TITLE
Pokedex Like GUI

### ISSUE THREAD

**Issue by RiftSpatial** [timinc-cobble/cobblemon-counter-1.4-fabric#8]
Since Counter is already capable of tracking what you've KOd/caught, perhaps we can add a simple gui where you can see each pokemon you've caught/KOd. It doesn't necessarily need to include every Pokemon, it'll just fill in as you catch/KO more, so you don't have empty spaces you can't fill. It could include the current streaks, and total counts of catches/KOs, perhaps even more info can be added if other mods, such as Unchained are installed, such as current Shiny Odds for that pokemon. We could also dream bigger, and perhaps even include the actual profile for each pokemon (Image and Dex entry), however, I think just starting as a basic gui for info from counter would be good, for utility.

**Comment by tmetcalfe89** [comment]
this is out of scope for this mod for the time being. this would very much be its own thing.
