### ISSUE TITLE
Add Functionality To Track Evolution (For Pokedex)

### ISSUE THREAD

**Issue by RiftSpatial** [timinc-cobble/cobblemon-counter-1.4-fabric#9]
Just add simple functionality that allows the mod to keep track of everything you've evolved. This would allow the future Pokedex to properly register pokemon through evolution. The number may be used for other mods as well, but I have no examples at this time.

**Comment by tmetcalfe89** [comment]
given the way the mod's leaning, and the scope of this mod, not interested in this. other mods can listen to the EVOLUTION_COMPLETE event as of 1.4
